"use client";

import { useProviderInfo } from "@/lib/hooks/use-provider-info";

/**
 * Honest data-source indicator: shows SIMULATED whenever quotes come from the
 * mock engine, LIVE only when a real feed is connected.
 */
export function DataSourceBadge() {
  const info = useProviderInfo();
  if (!info) return null;

  if (info.isSimulated) {
    return (
      <span
        className="inline-flex items-center gap-1 rounded-full border border-warn/40 bg-warn-muted px-2.5 py-1 text-[11px] font-medium text-warn"
        title={
          info.fallbackReason ??
          "All market data is generated by the in-browser simulator."
        }
      >
        <span className="h-1.5 w-1.5 rounded-full bg-warn" />
        SIMULATED
      </span>
    );
  }
  const connected = info.connectionState === "connected";
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[11px] font-medium ${
        connected
          ? "border-up/40 bg-up-muted text-up"
          : "border-border bg-surface-2 text-ink-3"
      }`}
      title={`${info.displayName} — ${info.connectionState}`}
    >
      <span className={`h-1.5 w-1.5 rounded-full ${connected ? "bg-up" : "bg-ink-3"}`} />
      {connected ? "LIVE" : info.connectionState.toUpperCase()}
    </span>
  );
}
